import pandas as pd 
import matplotlib.pyplot as plt

DF_BUY=pd.read_csv('BUY_BTCUSD.csv', encoding = "ISO-8859-1")
DF_BUY['index_col'] = DF_BUY.index

DF_SELL=pd.read_csv('SELL_BTCUSD.csv', encoding = "ISO-8859-1")
DF_SELL['index_col'] = DF_SELL.index


#for k in DF_SELL['index_col'] :
#    BTC_BALANCE = BTC_BALANCE + DF_SELL['TRADE_SIZE'][k]
#    
#for j in DF_BUY['index_col'] :
#     BTC_BALANCE = BTC_BALANCE - DF_BUY['TRADE_SIZE'][j]

#BTC_BALANCE_CHANGE=[]

T = DF_BUY['TIMESTAMP'][0]
t = DF_SELL['TIMESTAMP'][0]

ZERO_TIME = min(t,T)

TIME_INTERVAL=480000

END_TIME=ZERO_TIME+TIME_INTERVAL

CONTAINER=[]
EXTRA_COUNTER_SELL=0
COUNTER=0
PROFICITE_BOX=[]

SUMM_PROFICITE = 0
SUMM_VALUE_PROFICITE=0
VALUE_PROFICITE=[]

k=0
for k in DF_SELL['index_col'] :
    
    if  DF_SELL['TIMESTAMP'][k] >= END_TIME :
        END_TIME=END_TIME+TIME_INTERVAL
        COUNTER=COUNTER+1
        
        SUMM_VALUE_PROFICITE=SUMM_VALUE_PROFICITE+DF_SELL['PRICE'][k]*DF_SELL['TRADE_SIZE'][k]
        VALUE_PROFICITE.append(SUMM_VALUE_PROFICITE)
        
        CONTAINER.append(EXTRA_COUNTER_SELL)
        EXTRA_COUNTER_SELL = EXTRA_COUNTER_SELL + 1
        #print(EXTRA_COUNTER)
        
        SUMM_PROFICITE = SUMM_PROFICITE + DF_SELL['TRADE_SIZE'][k]
        PROFICITE_BOX.append(SUMM_PROFICITE)
        
        COUNTER=0
        SUMM_PROFICITE=0
        SUMM_VALUE_PROFICITE=0
        
    else :
        COUNTER=COUNTER+1
        SUMM_PROFICITE = SUMM_PROFICITE + DF_SELL['TRADE_SIZE'][k]
        SUMM_VALUE_PROFICITE=SUMM_VALUE_PROFICITE+DF_SELL['PRICE'][k]*DF_SELL['TRADE_SIZE'][k]
#CONTAINER=[]
EXTRA_COUNTER_BUY=0
COUNTER=0
DEFICITE_BOX=[]

SUMM_DEFICITE = 0
SUMM_VALUE_DEFICITE=0
VALUE_DEFICITE=[]

END_TIME=ZERO_TIME+TIME_INTERVAL
K=0

for K in DF_BUY['index_col'] :
    
    if  DF_BUY['TIMESTAMP'][K] >= END_TIME :
        END_TIME=END_TIME+TIME_INTERVAL
        COUNTER=COUNTER+1
        
        #CONTAINER.append(EXTRA_COUNTER_BUY)
        #EXTRA_COUNTER_BUY=EXTRA_COUNTER_BUY+1
        #print(EXTRA_COUNTER)
        
        SUMM_VALUE_DEFICITE=SUMM_VALUE_DEFICITE+DF_BUY['PRICE'][K]*DF_BUY['TRADE_SIZE'][K]
        VALUE_DEFICITE.append(SUMM_VALUE_DEFICITE)
        
        SUMM_DEFICITE = SUMM_DEFICITE + DF_BUY['TRADE_SIZE'][K]
        DEFICITE_BOX.append(SUMM_DEFICITE)
        
        COUNTER=0
        SUMM_DEFICITE=0
        SUMM_VALUE_DEFICITE=0
    else :
        COUNTER=COUNTER+1
        SUMM_DEFICITE = SUMM_DEFICITE + DF_BUY['TRADE_SIZE'][K]  

BTC_BALANCE_V1=[]
BTC_BALANCE_START=0
BTC_BALANCE_V2=[]
BTC_BALANCE_V3=[]
BTC_VALUE_START=0

MAX=0

t=0
for t in CONTAINER :
    #print(t)
    BTC_BALANCE_PER_INTERVAL = PROFICITE_BOX[t] - DEFICITE_BOX[t]
    BTC_BALANCE_V1.append(BTC_BALANCE_PER_INTERVAL)
    
    BTC_BALANCE_START = BTC_BALANCE_START + BTC_BALANCE_PER_INTERVAL
    BTC_BALANCE_V2.append(BTC_BALANCE_START)
    
    if MAX < VALUE_DEFICITE[t] : MAX=VALUE_DEFICITE[t] 
    
    BTC_VALUE_START=BTC_VALUE_START + VALUE_DEFICITE[t]-VALUE_PROFICITE[t]
    BTC_BALANCE_V3.append(BTC_VALUE_START)
    
#plt.plot(CONTAINER,BTC_BALANCE_V1)
#plt.plot(CONTAINER,BTC_BALANCE_V2)
#plt.plot(CONTAINER,DEFICITE_BOX)
#plt.plot(CONTAINER,PROFICITE_BOX)
plt.plot(CONTAINER,BTC_BALANCE_V3)